### ISSUE TITLE
Metric contexts: extend the MLFlow `GetMetricHistory` and `GetMetricHistories` endpoints to filter the query down based on the new `context` field

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#358]
- request: context field, optional, use for filtering when present and not empty
- filtering is done by asking the DB engine to match metrics where the requested context is a _subset_ of the recorded context
- For MVP only one level of searching is required, deeper structures will follow in new tickets.

**Comment by suprjinx** [comment]
Implemented for `GetMetricHistories`, which accepts a json request body so it's easy to add a context map field. `GetMetricHistory` is tricky, because it is only parsing query params and we don't have a good way to take a map/dictionary in the url query.

See https://github.com/gofiber/fiber/issues/2524 -- not implemented
