### ISSUE TITLE
Metric contexts: figure out how to best wrap/extend the MLFlow client API

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#362]
#209 and #363 will require us to wrap/extend the MLFlow client API in our Python package. This issue is about figuring out the best approach for shipping that in our Python package.

**Comment by fabiovincenzi** [comment]
I've created a package called `fasttrackml`. 
This package allows users to access all the functionalities of MLFlow while introducing an additional function, `log_metric_with_context`. 
This function retains the same parameters as `log_metric` but also accepts a `dict` representing the context. 
In implementing this, I followed the existing structure of MLFlow for managing metric log, creating subclasses of the existing ones. I've created a new entity called `Metric_with_context` which is basically equal to a normal `Metric` but has a new `context` field. 

- `fluent_context_support.log_metric_with_context` --> Log a metric with context under the current run. If no run is active, this method will create a new active run
- `MlflowClientExtend` --> is a sub-class of `MlflowClient` which provides `log_metric_with_context` method
- `ContextsupportStore` --> is a sub-class of `RestStore` allow us to create a json for the log metric with context request. In order to enable the new metric to be serialized in JSON format, I have also written a proto file for the `metric_with_context` .

all the changes can be found here: https://github.com/fabiovincenzi/fasttrack/tree/python-mlflow-wrapper

**Comment by jgiannuzzi** [comment]
Very interesting @fabiovincenzi!
Here are a few questions:
* could you try this with renaming `log_metric_with_context` to `log_metric` but with the additional optional named parameter `context`?
* is there any way to serialize to JSON without having to copy over the protos? we don't have to support databricks implementation, so we may as well veer away from this hard-to-maintain mess
* could you please give an example of what the UX looks like with an example script that logs metrics with contexts?

**Comment by fabiovincenzi** [comment]
Okay @jgiannuzzi, now the `MLFlow` `log_metric` has been overridden with our new implementation including an optional `context` parameter.
I removed `scalapb` and `databricks` protos by importing them directly from mlflow.

Here is an example of the UX:
```python
from random import randint, random

import fasttrackml
from fasttrackml import log_metric, log_param

fasttrackml.set_tracking_uri("http://localhost:5000")
fasttrackml.set_experiment("my-experiment")


if __name__ == "__main__":
    # Log a parameter (key-value pair)
    log_param("param1", randint(0, 100))

    # Log a metric without context
    log_metric("foo", random())
    # Log a metric with context
    log_metric("foo", random() + 1, context={'subset': 'train'})
```

**Comment by fabiovincenzi** [comment]
New changes made for:

- serializing the new metrics with context without using `photos`
- importing all of the `mlflow` methods and overriding them with custom `log_metric`

https://github.com/fabiovincenzi/fasttrack/tree/python-mlflow-wrapper
