### ISSUE TITLE
Add support for basic artifact logging

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/fasttrackml#6]
Many popular frameworks (Like Sklearn) require artifact support for autologging to work. We should add support for this.

[Scenario 4 ("MLflow with remote Tracking Server, backend and artifact stores")](https://mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores) requires us to implement ListArtifacts "for real" so that it can list the objects at a given s3 path.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/FML-18) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Start w/S3 support. Goal: replicate MLFlow logging. @jgiannuzzi to add an example here.

**Comment by jgiannuzzi** [comment]
Have a look at https://mlflow.org/docs/latest/tracking.html#how-runs-and-artifacts-are-recorded.
We want to support (in this order): scenarios 4, then 3, then 5.

[Scenario 4 ("MLflow with remote Tracking Server, backend and artifact stores")](https://mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores) requires us to implement ListArtifacts "for real" so that it can list the objects at a given s3 path.
[Scenario 3 ("MLflow on localhost with Tracking Server")](https://mlflow.org/docs/latest/tracking.html#scenario-3-mlflow-on-localhost-with-tracking-server) is the same, but for local files — so just listing a directory, but making sure we don't introduce any path traversal vulnerability.
[Scenario 5 ("MLflow Tracking Server enabled with proxied artifact storage access")](https://mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access) is more involved and out of the scope of this particular issue. It would require implementing [these 4 endpoints](https://github.com/mlflow/mlflow/blob/v2.4.1/mlflow/protos/mlflow_artifacts.proto).
